---
- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}jumpbox/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: Install Packages
  apt:
    name:
      - xfce4
      - xrdp
      - smbclient
      - gvfs
      - gvfs-backends
      - sshfs
      - gedit
      - chromium-browser
      - evince
      - xfce4-goodies
    update_cache: true
    state: latest

- name: Create Chromium managed policy directory
  file:
    path: /etc/opt/chromium/policies/managed
    state: directory
    mode: -w

- name: Install the Chromium policy
  copy:
    src: "{{ content_folder }}jumpbox/browser_policies/"
    dest: /etc/chromium/policies/managed/

- name: Create the {{ user_acct_name }} user
  user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pw_encrypted }}"
    shell: "{{ users_shell }}"

- name: Install the user home directory
  file:
    path: /home/{{ user_acct_name }}
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- name: Install the user ssh directory
  file:
    path: /home/{{ user_acct_name }}/.ssh
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0400

- name: Copy content to {{ user_acct_name }}'s home directory
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/"
    dest: /home/{{ user_acct_name }}/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- name: Copy ssh content to {{ user_acct_name }}'s home directory
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/.ssh/"
    dest: /home/{{ user_acct_name }}/.ssh/

- name: Copy content to {{ user_acct_name }}'s Desktop
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/Desktop/"
    dest: /home/{{ user_acct_name }}/Desktop/

- name: Create the player accounts
  user:
    name: "{{ item }}"
    password: "{{ player_pwd }}"
    shell: "{{ users_shell }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Copy updated xfce-keyboard-shortcuts file
  copy:
    src: "{{ content_folder }}jumpbox/xfce4-keyboard-shortcuts.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- name: Setup xsession for the player accounts
  command: "echo xfce4-session >~{{ item }}/.xsession && chown {{ item }}:{{ item }} ~{{ item }}/.xsession"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- template:
    src: templates/sesman.ini.j2
    dest: /etc/xrdp/sesman.ini

- name: Set default panel config for all users
  copy:
    src: "{{ content_folder }}jumpbox/xfce4-panel.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- service:
    name: xrdp
    state: restarted

- name: Copy the updated bashrd ile for all players
  copy:
    src: "{{ content_folder }}jumpbox/bashrc"
    dest: /home/{{ item }}/.bashrc
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Install 1NTERRUPT directory
  file:
    path: "/home/{{ item }}/Desktop/1NTERRUPT"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_sequence: count={{ player_count }} format={{ player_name_format }}
  become: true

- name: Copy files to 1NTERRUPT directory
  copy:
    src: "{{ content_folder }}jumpbox/1NTERRUPT/"
    dest: "/home/{{ item }}/Desktop/1NTERRUPT/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}
