---
- name: Get host variables
  include_vars:
    file: "{{ content_folder }}jumpbox/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: true

- name: Install Packages
  apt:
    name:
      - xfce4
      - xrdp
      - xfce4-goodies
      - smbclient
      - gvfs
      - gvfs-backends
      - sshfs
      - gedit
      - chromium-browser
      - evince
      - hxtools
      - rdesktop
    update_cache: true
    state: latest

# Browser tasks
- name: Create Chromium managed policy directory
  file:
    path: /etc/opt/chromium/policies/managed
    state: directory
    mode: -w

- name: Install the Chromium policy
  copy:
    src: "{{ content_folder }}jumpbox/browser_policies/"
    dest: /etc/chromium/policies/managed/

# User tasks
- name: Create the {{ user_acct_name }} user
  user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pwd | password_hash('sha512', password_salt ) }}"
    shell: "{{ users_shell }}"

# User ssh set up
- name: Install the user ssh directory
  file:
    path: /home/{{ user_acct_name }}/.ssh
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0700

- name: Copy ssh public key to {{ user_acct_name }}'s home directory
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/.ssh/id_rsa.pub"
    dest: /home/{{ user_acct_name }}/.ssh/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0644

- name: Copy ssh private key to {{ user_acct_name }}'s home directory
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/.ssh/id_rsa"
    dest: /home/{{ user_acct_name }}/.ssh/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0600

# Create and populate desktop content
- name: Copy content to {{ user_acct_name }}'s home directory
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/"
    dest: /home/{{ user_acct_name }}/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- name: Copy content to {{ user_acct_name }}'s Desktop
  copy:
    src: "{{ content_folder }}jumpbox/home/{{ user_acct_name }}/Desktop/"
    dest: /home/{{ user_acct_name }}/Desktop/

# Player tasks
- name: Create the player accounts
  user:
    name: "{{ item }}"
    password: "{{ player_acct_pwd | password_hash('sha512', password_salt ) }}"
    shell: "{{ users_shell }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Copy the updated bashrc files
  # This colorizes the prompt to help differentiate systems when using
  # the command line
  copy:
    src: "{{ content_folder }}/jumpbox/bashrc"
    dest: "/home/{{ item }}/.bashrc"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Copy background image into place
  copy:
    src: "{{ content_folder }}jumpbox/images/TakeBackHack.svg"
    dest: /user/share/backgrounds/

- name: Update the desktop background
  # This changes the default xfce4 desktop to help differentiate systems
  # when using RDP to connect to different instances
  copy:
    src: "{{ content_folder }}/jumpbox/xfce4/xfce4-desktop.xml"
    dest: "/home/{{ item }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Install the START_HERE directory
  file:
    path: "/home/{{ item }}/Desktop/START_HERE"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Copy files to the START_HERE directory
  copy:
    src: "{{ content_folder }}jumpbox/1NTERRUPT/"
    dest: "/home/{{ item }}/Desktop/START_HERE/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

# Set up the remote desktop server
- name: Install the RDP server
  include_role:
    name: rdp_server

- name: Setup xsession for the player accounts
  command: "echo xfce4-session >~{{ item }}/.xsession && chown {{ item }}:{{ item }} ~{{ item }}/.xsession"
  with_sequence: count={{ player_count }} format={{ player_name_format }}

- name: Reboot the server
  reboot:
    reboot_timeout: 3600
  become: true
