---
- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}pubfile01/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pw_encrypted }}"

- user:
    name: "{{ admin_acct_name }}"
    password: "{{ admin_acct_pw_encrypted }}"

- copy:
    src: "{{ content_folder }}pubfile01/"
    dest: /srv/samba/

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: pubfile01
    samba_server_string: 'Welcome to the {{ company_name }} public file server'
    samba_workgroup: Public

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "public fileshare"
        public: yes
        guest_ok: yes
        read_only: yes

      - name: private
        comment: "private fileshare"
        public: no
        guest_ok: no
        read_only: yes
        valid_users: "{{ admin_acct_name }}"
    samba_users:
      -
        name: "{{ admin_acct_name }}"
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  30363762623230656436376432653030376565666333353036663334646566623966643361326466
                  3633393964626136303034363863623630613635306238300a326534363437323663336435363262
                  32646635363631626238303966396338323965653564666636306433643930373062373031383834
                  6333343364646635300a343766326233633866626637383939666630666561616137623665306561
                  3331
