---

  - name: Install Packages
    apt:
      name:
        - xfce4
        - xrdp
        - xfce4-goodies
      update_cache: true
      state: latest
    notify:
      - Restart xrdp

  - name: Copy updated xfce-keyboard-shortcuts file
    copy:
      src: "{{ content_folder }}jumpbox/xfce4/xfce4-keyboard-shortcuts.xml"
      dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

  - name: Set default panel config for all users
    copy:
      src: "{{ content_folder }}jumpbox/xfce4/xfce4-panel.xml"
      dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/
