---
- name: Get variables
  include_vars:
    file: ./files/vars.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - xfce4
    - xrdp
    - nmap
    - smbclient
    - gvfs
    - gvfs-backends
    - sshfs
    - gedit
    - chromium-browser
    - evince
    - wireshark
    - whois
    - traceroute
    - exiftool
    - xfce4-goodies
    - htop

- name: Create Chromium managed policy directory
  file:
    path: /etc/opt/chromium/policies/managed
    state: directory
    mode: -w

- name: Install the Chromium policy
  copy:
    src: "{{ content_folder }}toolsJumpbox/browser_policies/"
    dest: /etc/chromium/policies/managed/

- user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ shell }}"
  loop: "{{ user_acct }}"

- name: Install the user home directory
  file:
    path: /home/{{ item.name }}
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ user_acct }}"

- name: Install the user ssh directory
  file:
    path: /home/{{ item.name }}/.ssh
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}toolsJumpbox/home/{{ item.name }}/"
    dest: /home/{{ item.name }}/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}toolsJumpbox/home/{{ item.name}}/.ssh/"
    dest: /home/{{ item.name }}/.ssh/
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}toolsJumpbox/home/{{ item.name }}/Desktop/"
    dest: /home/{{ item.name }}/Desktop/
  loop: "{{ user_acct }}"

- name: Create the player accounts
  user:
    name: "{{ item }}"
    password: $1$1nterrup$1d2n7Q0.r54s
    shell: "{{ shell }}"
  with_sequence: count={{ user_count }} format=player%01d

- name: Copy updated xfce-keyboard-shortcuts file
  copy:
    src: "{{ content_folder }}toolsJumpbox/xfce4-keyboard-shortcuts.xml"
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- name: Setup xsession for the player accounts
  command: "echo xfce4-session >~{{ item }}/.xsession && chown {{ item }}:{{ item }} ~{{ item }}/.xsession"
  with_sequence: count={{ user_count }} format=player%01d

- template:
    src: templates/sesman.ini.j2
    dest: /etc/xrdp/sesman.ini

- name: Set default panel config for all users
  copy:
    src: "{{ content_folder }}toolsJumpbox/xfce4-panel.xml" 
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- service:
    name: xrdp
    state: restarted

- name: Install 1NTERRUPT directory
  file:
    path: "/home/{{ item }}/Desktop/1NTERRUPT"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
  with_sequence: count={{ user_count }} format=player%01d

- name: Copy files to 1NTERRUPT directory
  copy:
    src: "{{ content_folder }}toolsJumpbox/1NTERRUPT/"
    dest: "/home/{{ item }}/Desktop/1NTERRUPT/"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_sequence: count={{ user_count }} format=player%01d
