---
- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - xfce4
    - xrdp
    - nmap
    - smbclient
    - gvfs
    - gvfs-backends
    - sshfs
    - gedit
    - firefox
    - evince
    - wireshark
    - whois
    - traceroute
    - exiftool
    - xfce4-goodies
    - bsdgames
    - htop

- name: add all tools users
  user:
    name: "tools{{ item }}"
    password: $1$1nterrup$CZrFw7SwWrWI.mJzmeAKc1
  with_sequence: start=0 end=9

- name: setup xsession for tools user
  command: "echo xfce4-session >~tools{{ item }}/.xsession && chown tools{{ item }}:tools{{ item }} ~tools{{ item }}/.xsession"
  with_sequence: start=0 end=9

- service:
    name: xrdp
    state: restarted

- name: Install 1NTERRUPT directory
  file:
    path: "/home/tools{{ item }}/Desktop/1NTERRUPT"
    state: directory
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
    mode: 0755
  with_sequence: start=0 end=9

- name: Copy files to 1NTERRUPT directory
  copy:
    src: /tmp/scenario_support/toolsJumpbox/1NTERRUPT/
    dest: "/home/tools{{ item }}/Desktop/1NTERRUPT/"
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
  with_sequence: start=0 end=9
