---
- name: Set the hostname
  hostname:
    name: tools
  become: yes

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - xfce4
    - xrdp
    - nmap
    - smbclient
    - gvfs
    - gvfs-backends
    - sshfs
    - gedit
    - firefox

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- user:
    name: tools
    password: $1$1nterrup$q7vyWA46q5SFch.X81I.V/
    groups: wheel

- name: setup xsession for tools user
  command: echo xfce4-session >~tools/.xsession && chown tools:tools ~tools/.xsession

- service:
    name: xrdp
    state: restarted

- apt_key:
    url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
    state: present

- apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: 'google-chrome'

- name: install chrome
  apt:
    name: google-chrome-stable
    state: latest
    update_cache: yes
    allow_unauthenticated: yes

- name: Install 1NTERRUPT directory
  file:
    path: "/home/tools/Desktop/1NTERRUPT"
    state: directory
    owner: tools
    group: tools
    mode: 0755

- name: Copy files to 1NTERRUPT directory
  copy:
    src: /tmp/scenario_support/toolsJumpbox/1NTERRUPT/
    dest: /home/tools/Desktop/1NTERRUPT/
    owner: tools
    group: tools

