---
- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - xfce4
    - xrdp
    - nmap
    - smbclient
    - gvfs
    - gvfs-backends
    - sshfs
    - gedit
    - chromium-browser
    - evince
    - wireshark
    - whois
    - traceroute
    - exiftool
    - xfce4-goodies
    - htop

- name: Create Chromium managed policy directory
  file:
    path: /etc/opt/chromium/policies/managed
    state: directory
    mode: -w

- name: Install the Chromium policy
  copy:
    src: /tmp/scenario_support/toolsJumpbox/browser_policies/
    dest: /etc/chromium/policies/managed/

- user:
    name: harrydavis
    password: $1$1nterrup$DMzrGjqazmuwmApH1wSIl/
    shell: /bin/bash

- name: Install Harry Davis home directory
  file:
    path: "/home/harrydavis/"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0755

- name: Install Harry Davis ssh directory
  file:
    path: "/home/harrydavis/.ssh"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0700

- copy:
    src: /tmp/scenario_support/toolsJumpbox/home/harrydavis/
    dest: /home/harrydavis/
    owner: harrydavis
    group: harrydavis
    mode: 0755

- copy:
    src: /tmp/scenario_support/toolsJumpbox/home/harrydavis/.ssh/
    dest: /home/harrydavis/.ssh/

- copy:
    src: /tmp/scenario_support/toolsJumpbox/home/harrydavis/Desktop/
    dest: /home/harrydavis/Desktop/

- name: add all tools users
  user:
    name: "tools{{ item }}"
    password: $1$1nterrup$CZrFw7SwWrWI.mJzmeAKc1
    shell: /bin/bash
  with_sequence: start=0 end=32

- name: Copy updated xfce-keyboard-shortcuts file
  copy:
    src: /tmp/scenario_support/toolsJumpbox/xfce4-keyboard-shortcuts.xml
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- name: setup xsession for tools user
  command: "echo xfce4-session >~tools{{ item }}/.xsession && chown tools{{ item }}:tools{{ item }} ~tools{{ item }}/.xsession"
  with_sequence: start=0 end=32

- template:
    src: templates/sesman.ini.j2
    dest: /etc/xrdp/sesman.ini

- name: Set default panel config for all users
  copy:
    src: /tmp/scenario_support/toolsJumpbox/xfce4-panel.xml 
    dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/

- service:
    name: xrdp
    state: restarted

- name: Install 1NTERRUPT directory
  file:
    path: "/home/tools{{ item }}/Desktop/1NTERRUPT"
    state: directory
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
    mode: 0755
  with_sequence: start=0 end=32

- name: Copy files to 1NTERRUPT directory
  copy:
    src: /tmp/scenario_support/toolsJumpbox/1NTERRUPT/
    dest: "/home/tools{{ item }}/Desktop/1NTERRUPT/"
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
  with_sequence: start=0 end=32
