---
- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - xfce4
    - xrdp
    - nmap
    - smbclient
    - gvfs
    - gvfs-backends
    - sshfs
    - gedit
    - firefox
    - evince

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'

- name: add all tools users
  user:
    name: "tools{{ item }}"
    password: $1$1nterrup$q7vyWA46q5SFch.X81I.V/
    groups: wheel
  with_sequence: start=0 end=32


- name: setup xsession for tools user
  command: "echo xfce4-session >~tools{{ item }}/.xsession && chown tools{{ item }}:tools{{ item }} ~tools{{ item }}/.xsession"
  with_sequence: start=0 end=32

- service:
    name: xrdp
    state: restarted

- name: Install 1NTERRUPT directory
  file:
    path: "/home/tools{{ item }}/Desktop/1NTERRUPT"
    state: directory
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
    mode: 0755
  with_sequence: start=0 end=32

- name: Copy files to 1NTERRUPT directory
  copy:
    src: /tmp/scenario_support/toolsJumpbox/1NTERRUPT/
    dest: "/home/tools{{ item }}/Desktop/1NTERRUPT/"
    owner: "tools{{ item }}"
    group: "tools{{ item }}"
  with_sequence: start=0 end=32
