---
- name: Set the hostname
  hostname:
    name: scoreboard
  become: yes

- name: Get variables
  include_vars:
    file: vars.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"

- name: Clone FacebookCTF git repository
  git:
    repo: 'https://github.com/facebook/fbctf.git'
    dest: /var/www/fbctf
    clone: yes
    update: no

- name: Paste customized language php file
  copy:
    src: /tmp/scenario_support/scoreboard/lang_en.php
    dest: /var/www/fbctf/src/language

- name: Paste customized controller php file
  copy:
    src: /tmp/scenario_support/scoreboard/IndexController.php
    dest: /var/www/fbctf/src/controllers

- name: Past the customized provision script
  copy:
    src: /tmp/scenario_support/scoreboard/provision.sh
    dest: /var/www/fbctf/extra/
    mode: "+x"

