---
- name: Set the hostname
  hostname:
    name: corpfile01
  become: yes

- name: Get variables
  include_vars:
    file: ./files/vars.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nmap
    - exiftool

- user: 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ shell }}"
  loop: "{{ user_acct }}"

- user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ shell }}"
  loop: "{{ admin_acct }}"

- name: Install user home directory
  file:
    path: /home/{{ item.name }}/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}corpfile01/home/{{ item.name }}/"
    dest: /home/{{ item.name }}/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ user_acct }}"

- name: Install user ssh directory
  file:
    path: /home/{{ item.name }}/.ssh
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}corpfile01/home/{{ item.name}}/.ssh/"
    dest: /home/{{ item.name}}/.ssh/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}corpfile01/shares/"
    dest: /srv/samba/

- name: create admin home directory
  file:
    path: /home/{{ item.name }}/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ admin_acct }}"

- name: copy files to admin home
  copy:
    src: "{{ content_folder }}corpfile01/home/{{ item.name }}/"
    dest: /home/{{ item.name }}/
  loop: "{{ admin_acct }}"

- name: Make marco script executable
  file:
    path: /home/{{ item.name }}/marco
    mode: +x
  loop: "{{ admin_acct }}"

- name: Make put script executable
  file:
    path: /home/{{ item.name }}/ftpput
    mode: +x
  loop: "{{ admin_acct }}"

- name: create marco cron job
  cron:
    name: Run marco
    minute: "*/5"
    job: /home/{{ item.name }}/marco
  loop: "{{ admin_acct }}"

- name: create ftpput cron job
  cron:
    name: Run put
    minute: "15"
    hour: "*"
    job: /home/{{ item.name }}/ftpput
  loop: "{{ admin_acct }}"

- file:
    path: /home/{{ item.name }}/.ssh/authorized_keys
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: touch
    mode: 0644
  loop: "{{ user_acct }}"

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: corpfile01
    samba_server_string: 'Welcome to the Utilitel file server'
    samba_workgroup: Utilitel

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "public fileshare"
        public: yes
        guest_ok: yes
        read_only: yes
 
      - name: private
        comment: "private fileshare"
        public: yes
        guest_ok: no
        read_only: yes
        valid_users: admin
    samba_users: 
      -
        name: admin
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  30363762623230656436376432653030376565666333353036663334646566623966643361326466
                  3633393964626136303034363863623630613635306238300a326534363437323663336435363262
                  32646635363631626238303966396338323965653564666636306433643930373062373031383834
                  6333343364646635300a343766326233633866626637383939666630666561616137623665306561
                  3331
