---
- name: Set the hostname
  hostname:
    name: corpfile01
  become: yes

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nmap
    - exiftool

- user: 
    name: harrydavis
    password: $1$1nterrup$DMzrGjqazmuwmApH1wSIl/
    shell: /bin/bash

- user:
    name: admin
    password: $1$1nterrup$C/d4YW3G5jTCvesbRnLeo/
    shell: /bin/bash

- name: Install Harry Davis home directory
  file:
    path: "/home/harrydavis/"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0755

- copy:
    src: /tmp/scenario_support/corpfile01/home/harrydavis/
    dest: /home/harrydavis/
    owner: harrydavis
    group: harrydavis
    mode: 0755

- name: Install Harry Davis ssh directory
  file:
    path: "/home/harrydavis/.ssh"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0700

- copy:
    src: /tmp/scenario_support/corpfile01/home/harrydavis/.ssh/
    dest: /home/harrydavis/.ssh/
    owner: harrydavis
    group: harrydavis
    mode: 0700

- copy:
    src: /tmp/scenario_support/corpfile01/shares/
    dest: /srv/samba/

- name: create admin home directory
  file:
    path: /home/admin/
    state: directory
    owner: admin
    group: admin
    mode: 0755

- name: copy files to admin home
  copy:
    src: /tmp/scenario_support/corpfile01/home/admin/
    dest: /home/admin/

- name: Make marco script executable
  file:
    path: /home/admin/marco
    mode: +x

- name: Make put script executable
  file:
    path: /home/admin/ftpput
    mode: +x

- name: create marco cron job
  cron:
    name: Run marco
    minute: "*/5"
    job: /home/admin/marco

- name: create ftpput cron job
  cron:
    name: Run put
    minute: "15"
    hour: "*"
    job: /home/admin/ftpput

- file:
    path: /home/harrydavis/.ssh/authorized_keys
    owner: harrydavis
    group: harrydavis
    state: touch
    mode: 0644

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: corpfile01
    samba_server_string: 'Welcome to the Utilitel file server'
    samba_workgroup: Utilitel

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "public fileshare"
        public: yes
        guest_ok: yes
        read_only: yes
 
      - name: private
        comment: "private fileshare"
        public: yes
        guest_ok: no
        read_only: yes
        valid_users: admin
    samba_users: 
      -
        name: admin
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  30363762623230656436376432653030376565666333353036663334646566623966643361326466
                  3633393964626136303034363863623630613635306238300a326534363437323663336435363262
                  32646635363631626238303966396338323965653564666636306433643930373062373031383834
                  6333343364646635300a343766326233633866626637383939666630666561616137623665306561
                  3331
