---
- name: Set the hostname
  hostname:
    name: corpfile01
  become: yes

- user: 
    name: harrydavis
    password: $1$1nterrup$DMzrGjqazmuwmApH1wSIl/

- user:
    name: admin
    password: $1$1nterrup$C/d4YW3G5jTCvesbRnLeo/

- name: Install Harry Davis home directory
  file:
    path: "/home/harrydavis/"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0755

- copy:
    src: /tmp/scenario_support/corpfile01/home/harrydavis/
    dest: /home/harrydavis/

- copy:
    src: /tmp/scenario_support/corpfile01/shares/
    dest: /srv/samba/

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: corpfile01
    samba_server_string: 'Welcome to the Utilitel file server'
    samba_workgroup: Utilitel

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "public fileshare"
        public: yes
        guest_ok: yes
        read_only: yes
 
      - name: private
        comment: "private fileshare"
        public: yes
        guest_ok: no
        read_only: yes
        valid_users: admin
    samba_users: 
      -
        name: admin
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  30363762623230656436376432653030376565666333353036663334646566623966643361326466
                  3633393964626136303034363863623630613635306238300a326534363437323663336435363262
                  32646635363631626238303966396338323965653564666636306433643930373062373031383834
                  6333343364646635300a343766326233633866626637383939666630666561616137623665306561
                  3331
