---
- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}corpfile01/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pw_encrypted }}"
    shell: "{{ users_shell }}"

- user:
    name: "{{ admin_acct_name }}"
    password: "{{ admin_acct_pw_encrypted }}"
    shell: "{{ users_shell }}"

- name: Install user home directory
  file:
    path: /home/{{ user_acct_name }}/
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- copy:
    src: "{{ content_folder }}corpfile01/home/{{ user_acct_name }}/"
    dest: /home/{{ user_acct_name }}/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- name: Install user ssh directory
  file:
    path: /home/{{ user_acct_name }}/.ssh
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0700

- copy:
    src: "{{ content_folder }}corpfile01/home/{{ user_acct_name }}/.ssh/"
    dest: /home/{{ user_acct_name}}/.ssh/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0700

- copy:
    src: "{{ content_folder }}corpfile01/shares/"
    dest: /srv/samba/

- name: create admin home directory
  file:
    path: /home/{{ admin_acct_name }}/
    state: directory
    owner: "{{ admin_acct_name }}"
    group: "{{ admin_acct_name }}"
    mode: 0755

- name: copy files to admin home
  copy:
    src: "{{ content_folder }}corpfile01/home/{{ admin_acct_name }}/"
    dest: /home/{{ admin_acct_name }}/

- name: Make marco script executable
  file:
    path: /home/{{ admin_acct_name }}/marco
    mode: +x

- name: Make put script executable
  file:
    path: /home/{{ admin_acct_name }}/ftpput
    mode: +x

- name: create marco cron job
  cron:
    name: Run marco
    minute: "*/5"
    job: /home/{{ admin_acct_name }}/marco

- name: create ftpput cron job
  cron:
    name: Run put
    minute: "15"
    hour: "*"
    job: /home/{{ admin_acct_name }}/ftpput

- file:
    path: /home/{{ user_acct_name }}/.ssh/authorized_keys
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    state: touch
    mode: 0644

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: corpfile01
    samba_server_string: 'Welcome to the {{ company_name }} file server'
    samba_workgroup: "{{ company_nick_name }}"

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "public fileshare"
        public: yes
        guest_ok: yes
        read_only: yes

      - name: private
        comment: "private fileshare"
        public: yes
        guest_ok: no
        read_only: yes
        valid_users: "{{ admin_acct_name }}"
    samba_users:
      -
        name: "{{ admin_acct_name }}"
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  30363762623230656436376432653030376565666333353036663334646566623966643361326466
                  3633393964626136303034363863623630613635306238300a326534363437323663336435363262
                  32646635363631626238303966396338323965653564666636306433643930373062373031383834
                  6333343364646635300a343766326233633866626637383939666630666561616137623665306561
                  3331
