---
- name: Get the host variables
  include_vars:
    file: "{{ content_folder }}/wikiserver/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: Copy static content
  copy:
    src: "{{ content_folder }}/wikiserver/"
    dest: "{{ wiki_directory }}"
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"

- name: Install Packages
  apt:
    name:
      - build-essential
      - npm
      - nodejs-legacy
      - mcrypt
      - nginx
    update_cache: true
    state: latest

- name: Install pm2
  npm:
    name: pm2
    global: yes
    production: yes

- name: Install Hazel wiki
  npm:
    name: hazel-wiki
    path: "{{ wiki_directory }}"
  register: npm_finished

- name: Copy dynamic content
  template:
    src: "{{ item }}"
    dest: "{{ wiki_directory }}/content/"
  with_fileglob: "/tmp/scenario_support/wikiserver/templates/*.md"

- name: Stop APP
  command: pm2 stop server.js --name app
  args:
    chdir: "{{ wiki_directory }}"
  become: true
  ignore_errors: yes
  when: npm_finished.changed
  register: app_stopped

- name: Start APP
  command: pm2 start server.js --name app
  args:
    chdir: "{{ wiki_directory }}"
  become: true
  ignore_errors: yes
  when: app_stopped.changed

- name: disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Copy nginx template
  template:
    src: "{{ content_folder }}wikiserver/templates/nginx.j2"
    dest: /etc/nginx/sites-enabled/{{ hostname }}

- name: Restart web server
  service:
    name: nginx
    state: restarted
