---
- name: Set the host
  hostname:
    name: backstage
  become: yes

- name: Setup ssh credentials
  aws_s3:
    bucket: 1nterrupt-util
    object: keys/utilitel-tools.pem
    dest: /home/ubuntu/.ssh/id_rsa
    mode: get

- file:
    path: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Create scenario folder
  file: path=/tmp/scenario_support/corp-file01 state=directory owner=ubuntu group=ubuntu 

- name: Download scenario support files
  command: "aws s3 cp --region=us-east-1 --recursive s3://1nterrupt-scenario-support /tmp/scenario_support/"

- name: Samba client
  apt:
    name: samba-client
    state: present
  become: true
