---
- name: Set the host
  hostname:
    name: backstage
  become: yes

- name: Get variables
  include_vars:
    file: ./files/vars.yml

- name: Update time zone
  timezone:
    name: "{{ timezone }}"
  become: yes

- name: Setup ssh credentials
  aws_s3:
    bucket: "{{ s3_bucket_keys }}"
    object: keys/{{ key_file }}
    dest: /home/ubuntu/.ssh/id_rsa
    mode: get

- file:
    path: /home/ubuntu/.ssh/id_rsa
    owner: ubuntu
    group: ubuntu
    mode: 0700

- name: Create scenario folder
  file:
    path: "{{ content_folder }}"
    state: directory 
    owner: ubuntu 
    group: ubuntu 

- name: Download scenario support files
  command: "aws s3 cp --region={{ aws_region }} --recursive s3://{{ s3_bucket_content }} {{ content_folder }}"
