---
- name: Load aws secrets
  include_vars: aws.yml

- name: Create aws credentials folder
  file: path=/home/ubuntu/.aws state=directory owner=ubuntu group=ubuntu 

- name: Create scenario folder
  file: path=/tmp/scenario_support state=directory owner=ubuntu group=ubuntu 

- name: Setup aws credentials
  template: src=credentials.j2 dest=/home/ubuntu/.aws/credentials
  become: yes

- name: List scenario support files
  s3: 
    mode=list
    bucket=1nterrupt-scenario-support
  register: scenario_support_items

- name: Download scenario support files
  s3:
    mode=get
    bucket=1nterrupt-scenario-support
    object={{ item  }}
    dest=/tmp/scenario_support
  with_items: scenario_support_items.s3_keys
