---
- name: Set the host
  hostname:
    name: backstage
  become: true

- name: Get regional variables
  include_vars:
    file: ./global_vars/regional.yml

- name: Get common variables
  include_vars:
    file: ./global_vars/common.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"
  become: true

- name: Setup ssh credentials
  aws_s3:
    bucket: "{{ s3_bucket_keys }}"
    object: keys/{{ key_file }}
    dest: /home/{{ installer_acct_name }}/.ssh/id_rsa
    mode: get

- name: Set ssh key permissions
  file:
    path: /home/{{ installer_acct_name }}/.ssh/id_rsa
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"
    mode: 0700

- name: Create all_hosts file
  file:
    path: /home/{{ installer_acct_name }}/ansible/all_hosts
    state: touch
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"

- name: Create scenario folder
  file:
    path: "{{ content_folder }}"
    state: directory
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"

- name: Download scenario support files
  command: "aws s3 cp --recursive s3://{{ s3_bucket_content }} {{ content_folder }}"
