---
- name: Set the hostname
  hostname:
    name: ops-pumpshmi01
  become: yes

- git:
    repo: https://github.com/1NTERRUPT/water-processing
    dest: /srv/pumpserver

- name: Setup server permissions
  command: chown -R ubuntu:ubuntu /srv/pumpserver
  become: yes

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - build-essential
    - npm
    - nodejs-legacy
    - git
    - mcrypt
    - nginx
    - curl
    - ruby-full
    - ruby-bundler
    - sqlite3 
    - libsqlite3-dev

- name: Install pumpserver
  bundler:
      state: present
      chdir: /srv/pumpserver
  become: no

- name: migrate database
  command: bundle exec rake db:migrate RAILS_ENV="production" chdir=/srv/pumpserver
  become: no

- name: tmp clear
  command: bundle exec rake tmp:clear RAILS_ENV="production" chdir=/srv/pumpserver
  become: no

- name: log clear
  command: bundle exec rake log:clear RAILS_ENV="production" chdir=/srv/pumpserver
  become: no

- name: setup seed data
  command: bundle exec rake db:seed RAILS_ENV="production" chdir=/srv/pumpserver
  become: no

  #- name: update cron jobs
  #  command: bundle exec whenever --update-crontab chdir=/srv/pumpserver
  #  become: yes

- name: disable default nginx site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-enabled/pumpserver

- template:
    src: templates/pumpserver.j2
    dest: /etc/init/pumpserver.conf
  become: yes

- service:
    name: pumpserver
    state: restarted

- service:
    name: nginx
    state: restarted

