---
- git:
    repo: https://github.com/1NTERRUPT/water-processing
    dest: /srv/pumpserver

- name: Setup server permissions
  command: chown -R ubuntu:ubuntu /srv/pumpserver
  become: yes

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - build-essential
    - npm
    - nodejs-legacy
    - git
    - mcrypt
    - nginx
    - curl
    - ruby2.4
    - ruby2.4-dev
    - ruby-switch
    - sqlite3 
    - libsqlite3-dev

- name: Set Ruby 2.4 as default
  command: ruby-switch --set ruby2.4
  become: yes

- apt: name=ruby-bundler update_cache=yes state=latest
  become: yes

- name: Install Bundler
  gem: name=bundler state=latest
  user_install: no
  executable: yes
  become: yes

- name: Really install bundler
  command: gem install bundler
  become: yes

- name: Install pumpserver
  bundler:
      state: present
      chdir: /srv/pumpserver
  become: no

- name: migrate database
  command: bundle exec rake db:migrate chdir=/srv/pumpserver
  become: no

- name: tmp clear
  command: bundle exec rake tmp:clear chdir=/srv/pumpserver
  become: no

- name: log clear
  command: bundle exec rake log:clear chdir=/srv/pumpserver
  become: no

- name: setup seed data
  command: bundle exec rake db:seed chdir=/srv/pumpserver
  become: no

- name: update cron jobs
  command: bundle exec whenever --update-crontab --set environment='development' chdir=/srv/pumpserver
  become: no

- name: disable default nginx site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-enabled/pumpserver

- template:
    src: templates/pumpserver.j2
    dest: /etc/init/pumpserver.conf
  become: yes

- service:
    name: pumpserver
    state: restarted

- service:
    name: nginx
    state: restarted

- name: Create generic ops user
  user:
    name: ops 
# Don't forget to set a password

- name: Create ops home directory
  file:
    path: /home/ops/
    state: directory
    owner: ops
    group: ops
    mode: 0755

- name: Copy content to ops home directory
  copy:
    src: /tmp/scenario_support/pumpshmi01/home/ops/
    dest: /home/ops/

- name: Make marco script executable
  file:
    path: /home/ops/marco
    mode: +x

- name: Make ftp script executable
  file:
    path: /home/ops/ftpput
    mode: +x

- name: Create marco cron job
  cron:
    name: Run marco
    minute: "*/1"
    hour: "*"
    job: "/home/ops/marco"

- name: Create ftp cron job
  cron:
    name: Run ftpput
    minute: "10"
    hour: "*"
    job: "/home/ops/ftpput"

