---
- git:
    repo: https://github.com/1NTERRUPT/water-processing
    dest: /srv/pumpserver

- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}pumpserver/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: Setup server permissions
  file:
    path: /srv/pumpserver/
    state: directory
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"
    recurse: yes

- name: Install Packages
  apt:
    name:
      - build-essential
      - npm
      - nodejs-legacy
      - mcrypt
      - nginx
      - ruby2.4
      - ruby2.4-dev
      - ruby-switch
      - sqlite3
      - libsqlite3-dev
    update_cache: true
    state: latest

- name: Set Ruby 2.4 as default
  command: ruby-switch --set ruby2.4
  become: yes

- name: Install the Ruby bundler
  apt:
    name: ruby-bundler
    update_cache: true
    state: latest
    force: true
  become: yes

- name: Really install bundler
  command: gem install bundler
  become: yes

- name: Install pumpserver
  bundler:
      state: present
      chdir: /srv/pumpserver
  become: no

- name: migrate database
  command: bundle exec rake db:migrate chdir=/srv/pumpserver
  become: no

- name: tmp clear
  command: bundle exec rake tmp:clear chdir=/srv/pumpserver
  become: no

- name: log clear
  command: bundle exec rake log:clear chdir=/srv/pumpserver
  become: no

- name: setup seed data
  command: bundle exec rake db:seed chdir=/srv/pumpserver
  become: no

- name: update cron jobs
  command: bundle exec whenever --update-crontab --set environment='development' chdir=/srv/pumpserver
  become: no

- name: disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-enabled/pumpserver

- template:
    src: templates/pumpserver.j2
    dest: /etc/init/pumpserver.conf
  become: yes

- service:
    name: pumpserver
    state: restarted

- service:
    name: nginx
    state: restarted

- name: Create generic ops user
  user:
    name: "{{ ops_acct_name }}"
    password: "{{ ops_acct_pw_encrytped }}"

- name: Create ops user home directory
  file:
    path: /home/{{ ops_acct_name }}/
    state: directory
    owner: "{{ ops_acct_name }}"
    group: "{{ ops_acct_name }}"
    mode: 0755

- name: Copy content to ops user home directory
  copy:
    src: "{{ content_folder }}pumpshmi01/home/{{ ops_acct_name }}/"
    dest: /home/{{ ops_acct_name }}/

- name: Make marco script executable
  file:
    path: /home/{{ ops_acct_name }}/marco
    mode: +x

- name: Make ftp script executable
  file:
    path: /home/{{ ops_acct_name }}/ftpput
    mode: +x

- name: Create marco cron job
  cron:
    name: Run marco
    minute: "*/1"
    hour: "*"
    job: /home/{{ ops_acct_name }}/marco

- name: Create ftp cron job
  cron:
    name: Run ftpput
    minute: "10"
    hour: "*"
    job: /home/{{ ops_acct_name }}/ftpput
