---
- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}picks/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- name: Install Packages
  apt:
    name:
      - build-essential
      - npm
      - nodejs-legacy
      - mcrypt
      - nginx
      - vsftpd
    update_cache: true
    state: latest

- copy:
    src: "{{ content_folder }}picks/www/"
    dest: /srv/picks/
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"

- copy:
    src: "{{ content_folder }}picks/ftp/"
    dest: /srv/ftp/
    owner: "{{ installer_acct_name }}"
    group: "{{ installer_acct_name }}"

- name: Create anonymous ftp user
  user:
    name: ftp_user
    group: ftp

- name: Create public upload directory
  file:
    path: /srv/ftp/uploads
    state: directory
    owner: ftp_user
    group: ftp
    mode: 0775

- copy:
    src: /tmp/scenario_support/picks/etc/
    dest: /etc/
    owner: root
    group: root

- user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pw_encrypted }}"

- user:
    name: "{{ admin_acct_name }}"
    password: "{{ admin_acct_pw_encrypted }}"

- name: Install web server
  npm:
    path: /srv/picks
  register: npm_finished

- name: disable default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-enabled/picks

- service:
    name: nginx
    state: restarted

- service:
    name: vsftpd
    state: restarted
