---
- name: Set the hostname
  hostname:
    name: picks
  become: yes

- name: Get variables
  include_vars:
    file: ./files/vars.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - build-essential
    - npm
    - nodejs-legacy
    - mcrypt
    - nginx
    - curl
    - vsftpd

- copy:
    src: "{{ content_folder }}picks/www/"
    dest: /srv/picks/
    owner: ubuntu
    group: ubuntu

- copy:
    src: "{{ content_folder }}picks/ftp/"
    dest: /srv/ftp/
    owner: ubuntu
    group: ubuntu

- name: Create anonymous ftp user
  user:
    name: ftp_user
    group: ftp

- name: Create public upload directory
  file:
    path: /srv/ftp/uploads
    state: directory
    owner: ftp_user
    group: ftp
    mode: 0775

- copy:
    src: /tmp/scenario_support/picks/etc/
    dest: /etc/
    owner: root
    group: root

- user: 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ user_acct }}"

- user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ admin_acct }}"

- name: Install web server
  npm:
    path: /srv/picks
  register: npm_finished

- name: disable default nginx site
  file: 
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-enabled/picks

- service:
    name: nginx
    state: restarted

- service:
    name: vsftpd
    state: restarted
