---
- hosts: all
  gather_facts: False

  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: tag_Name_fileserver
  become: true

  vars:
    samba_netbios_name: Fileserver
    samba_server_string: 'Welcome to the utilitel file server'
    samba_workgroup: Utilitel

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
      - name: public
        comment: "fileshare"
        guest_ok: yes
        read_only: yes
    
  roles: 
    - fileserver
    - samba
