---
- hosts: tag_name_fileserver
  become: true

  vars:
    samba_netbios_name: SAMBA_TEST
    samba_server_string: 'Welcome to the test file server'
    samba_workgroup: TESTGROUP

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
      - name: public
        comment: "fileshare"
        guest_ok: yes
        read_only: yes
    
  roles: 
    - samba
