---
- hosts: localhost
  connection: local
  gather_facts: False
  roles: 
    - backstage

- hosts: tag_Name_fileserver
  become: true
  roles: 
    - fileserver

- hosts: tag_Name_wikiserver
  become: true
  roles:
    - wikiserver
    
- hosts: tag_Name_tools
  become: true
  roles:
    - tools

- hosts: tag_Name_pumpserver
  become: true
  roles:
    - pumpserver
