---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - backstage

- hosts: all
  become: true
  tasks:

  - name: Get regional variables
    include_vars:
      file: ./global_vars/regional.yml

  - name: Get common variables
    include_vars:
      file: ./global_vars/common.yml

  - name: Install common packages
    apt:
      name:
        - htop
        - traceroute
        - whois
        - nmap
        - unzip
        - curl
        - exiftool
        - wireshark
      update_cache: true
      state: latest
    become: true

  # Create the Treasure Hunt admin account
  - name: Create the {{ THAdmin_acct_name }} user
    user:
      name: "{{ THAdmin_acct_name }}"
      password: "{{ THAdmin_acct_pwd | password_hash('sha512', password_salt ) }}"
      shell: "{{ users_shell }}"
    become: true

- hosts: tag_Name_pumpserver
  become: true
  roles:
    - pumpserver

- hosts: tag_Name_picks
  become: true
  roles:
    - picks

- hosts: tag_Name_billpay
  become: true
  roles:
    - billpay

- hosts: tag_Name_blogserver
  become: true
  roles:
    - blogserver

- hosts: tag_Name_corpfile01
  become: true
  roles:
    - corpfile01

- hosts: tag_Name_wikiserver
  become: true
  roles:
    - wikiserver

- hosts: tag_Name_jumpbox
  become: true
  roles:
    - jumpbox

- hosts: tag_Name_pubfile01
  become: true
  roles:
    - pubfile01

- hosts: tag_Name_opsfile01
  become: true
  roles:
    - opsfile01

- hosts: tag_Name_mailserver
  become: true
  roles:
    - mailserver

- hosts: tag_Name_scoreboard
  become: true
  roles:
    - scoreboard

- hosts: all
  become: true
  tasks:

  - name: Set time zone
    timezone:
      name: "{{ timezone }}"

  - name: Get IP and hostname
    setup:
      filter:
        - default_ipv4
        - hostname

  - name: Write hostnames and IPs to a file
    local_action:
      module: lineinfile
      path: /home/{{ installer_acct_name }}/ansible/all_hosts
      line: "{{ ansible_default_ipv4.address}}\t{{ ansible_hostname }}"
      insertafter: EOF

  - name: Copy the all_hosts file to all instances
    copy:
      src: ./all_hosts
      dest: /etc/hosts
    when: ansible_facts['hostname'] != "mailserver"

  - name: Update all of the software packages
    apt:
      force_apt_get: yes
      upgrade: full
      autoclean: yes
      autoremove: yes
    become: true

- name: Wrap it up
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: Clean up
    file:
      path: "{{ item }}"
      state: absent
    with_fileglob: "/home/ubuntu/.aws/*"
