---
- hosts: localhost
  connection: local
  gather_facts: False
  roles: 
    - backstage

- hosts: tag_Name_fileserver
  become: true
  roles: 
    - corp-file01

- hosts: tag_Name_wikiserver
  become: true
  roles:
    - wikiserver
    
- hosts: tag_Name_tools
  become: true
  roles:
    - tools
    - { role: fqdn, fqdn: "tools.utilitel.com", hostname: "tools" }

- hosts: tag_Name_pumpserver
  become: true
  roles:
    - pumpserver
    - { role: fqdn, fqdn: "ops-pumpshmi01.utilitel.com", hostname: "ops-pumpshmi01" }
