---
- name: Set the hostname
  hostname:
    name: opsfile01
  become: yes

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nmap
    - exiftool

- user: 
    name: harrydavis
    password: $1$1nterrup$DMzrGjqazmuwmApH1wSIl/

- user:
    name: ops
    password: $1$1nterrup$uSpFgWnBpgRAzEK0Yp0HA1

- name: Install Harry Davis home directory
  file:
    path: "/home/harrydavis/"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0755

- copy:
    src: /tmp/scenario_support/opsfile01/home/harrydavis/
    dest: /home/harrydavis/
    
- name: Install Harry Davis ssh directory
  file:
    path: "/home/harrydavis/.ssh"
    state: directory
    owner: harrydavis
    group: harrydavis
    mode: 0700

- copy:
    src: /tmp/scenario_support/corpfile01/home/harrydavis/.ssh/
    dest: /home/harrydavis/.ssh/
    owner: harrydavis
    group: harrydavis
    mode: 0700

- copy:
    src: /tmp/scenario_support/corpfile01/shares/
    dest: /srv/samba/

- file:
    path: /home/harrydavis/.ssh/authorized_keys
    owner: harrydavis
    group: harrydavis
    state: touch
    mode: 0644

- copy:
    src: /tmp/scenario_support/opsfile01/shares/
    dest: /srv/samba/

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: opsfile01
    samba_server_string: 'Operations file server RESTRICTED USE'
    samba_workgroup: Public

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
 
      - name: ops
        comment: "private fileshare"
        public: no
        guest_ok: no
        read_only: yes
        valid_users: ops
    samba_users: 
      -
        name: ops
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  39343736323966643731613464316335653430383233616163343533643130663530383937363964
                  6331303536626133366330383965623132356535643566650a333532373930333465363662393263
                  66363661663733396433333065386238313665666161623130663066613436386134373131343066
                  6362643963636332320a356231373237313035313664363962326534626666366564643065646535
                  6165
