---
- name: Set the hostname
  hostname:
    name: opsfile01
  become: yes

- name: Get variables
  include_vars:
    file: ./files/vars.yml

- name: Set time zone
  timezone:
    name: "{{ timezone }}"

- name: Install Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - nmap
    - exiftool

- user: 
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ shell }}"
  loop: "{{ user_acct }}"

- user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    shell: "{{ shell }}"
  loop: "{{ ops_acct }}"

- name: Install user home directory
  file:
    path: /home/{{ item.name }}/
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0755
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}opsfile01/home/{{ item.name }}/"
    dest: /home/{{ item.name }}/
  loop: "{{ user_acct }}"

- name: Install user ssh directory
  file:
    path: /home/{{ item.name }}/.ssh
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}opsfile01/home/{{ item.name }}/.ssh/"
    dest: /home/{{ item.name }}/.ssh/
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0700
  loop: "{{ user_acct }}"

- name: create ops home directory
  file:
    path: /home/ops
    state: directory
    owner: ops
    group: ops
    mode: 0755

- name: copy files to ops home
  copy:
    src: "{{ content_folder }}opsfile01/home/{{ item.name }}/"
    dest: /home/{{ item.name }}/
  loop: "{{ ops_acct }}"

- name: Make marco script executable
  file:
    path: /home/{{ item.name }}/marco
    mode: +x
  loop: "{{ ops_acct }}"

- name: Make put script executable
  file:
    path: /home/{{ item.name }}/ftpput
    mode: +x
  loop: "{{ ops_acct }}"

- name: Create marco cron job
  cron:
    name: Run marco
    minute: "*/10"
    job: /home/{{ item.name }}/marco
  loop: "{{ ops_acct }}"

- name: Create put cron job
  cron:
    name: Run ftpput
    minute: "12"
    hour: "*"
    job: /home/{{ item.name }}/ftpput
  loop: "{{ ops_acct }}"

- copy:
    src: "{{ content_folder }}opsfile01/shares/"
    dest: /srv/samba/

- file:
    path: /home/{{ item.name }}/.ssh/authorized_keys
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    state: touch
    mode: 0644
  loop: "{{ user_acct }}"

- copy:
    src: "{{ content_folder }}opsfile01/shares/"
    dest: /srv/samba/

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: opsfile01
    samba_server_string: 'Operations file server RESTRICTED USE'
    samba_workgroup: Public

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:
 
      - name: ops
        comment: "private fileshare"
        public: no
        guest_ok: no
        read_only: yes
        valid_users: ops
    samba_users: 
      -
        name: ops
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  39343736323966643731613464316335653430383233616163343533643130663530383937363964
                  6331303536626133366330383965623132356535643566650a333532373930333465363662393263
                  66363661663733396433333065386238313665666161623130663066613436386134373131343066
                  6362643963636332320a356231373237313035313664363962326534626666366564643065646535
                  6165
