---
- name: Get variables
  include_vars:
    file: ./global_vars/common.yml

- name: Get host variables
  include_vars:
    file: "{{ content_folder }}opsfile01/host_vars/vars.yml"

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  become: yes

- user:
    name: "{{ user_acct_name }}"
    password: "{{ user_acct_pw_encrypted }}"
    shell: "{{ users_shell }}"

- user:
    name: "{{ ops_acct_name }}"
    password: "{{ ops_acct_pw_encrytped }}"
    shell: "{{ users_shell }}"

- name: Install user home directory
  file:
    path: /home/{{ user_acct_name }}/
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0755

- copy:
    src: "{{ content_folder }}opsfile01/home/{{ user_acct_name }}/"
    dest: /home/{{ user_acct_name }}/

- name: Install user ssh directory
  file:
    path: /home/{{ user_acct_name }}/.ssh
    state: directory
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0700

- copy:
    src: "{{ content_folder }}opsfile01/home/{{ user_acct_name }}/.ssh/"
    dest: /home/{{ user_acct_name }}/.ssh/
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    mode: 0700

- name: create ops home directory
  file:
    path: /home/{{ ops_acct_name }}
    state: directory
    owner: "{{ ops_acct_name }}"
    group: "{{ ops_acct_name }}"
    mode: 0755

- name: copy files to ops home
  copy:
    src: "{{ content_folder }}opsfile01/home/{{ ops_acct_name }}/"
    dest: /home/{{ ops_acct_name }}/

- name: Make marco script executable
  file:
    path: /home/{{ ops_acct_name }}/marco
    mode: +x

- name: Make put script executable
  file:
    path: /home/{{ ops_acct_name }}/ftpput
    mode: +x

- name: Create marco cron job
  cron:
    name: Run marco
    minute: "*/10"
    job: /home/{{ ops_acct_name }}/marco

- name: Create put cron job
  cron:
    name: Run ftpput
    minute: "12"
    hour: "*"
    job: /home/{{ ops_acct_name }}/ftpput

- copy:
    src: "{{ content_folder }}opsfile01/shares/"
    dest: /srv/samba/

- file:
    path: /home/{{ user_acct_name }}/.ssh/authorized_keys
    owner: "{{ user_acct_name }}"
    group: "{{ user_acct_name }}"
    state: touch
    mode: 0644

- copy:
    src: "{{ content_folder }}opsfile01/shares/"
    dest: /srv/samba/

- name: setup samba
  include_role:
    name: samba
  vars:
    samba_netbios_name: opsfile01
    samba_server_string: 'Operations file server RESTRICTED USE'
    samba_workgroup: Public

    samba_load_homes: true
    samba_load_printers: false
    samba_create_varwww_symlinks: true

    samba_log: /var/log/samba.log
    samba_log_size: 60000

    samba_map_to_guest: Never

    samba_shares_root: /srv/samba
    samba_shares:

      - name: "{{ ops_acct_name }}"
        comment: "private fileshare"
        public: no
        guest_ok: no
        read_only: yes
        valid_users: "{{ ops_acct_name }}"
    samba_users:
      -
        name: "{{ ops_acct_name }}"
        password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  39343736323966643731613464316335653430383233616163343533643130663530383937363964
                  6331303536626133366330383965623132356535643566650a333532373930333465363662393263
                  66363661663733396433333065386238313665666161623130663066613436386134373131343066
                  6362643963636332320a356231373237313035313664363962326534626666366564643065646535
                  6165
